# Generated by Django 5.1.4 on 2024-12-27 14:15

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('client_name', models.CharField(max_length=255)),
                ('clickup_folder_id', models.CharField(blank=True, max_length=255, null=True)),
                ('frame_folder_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, editable=False, null=True)),
                ('final_approved_frame_folder', models.CharField(blank=True, max_length=255, null=True)),
                ('client_email', models.EmailField(error_messages={'unique': 'A customer with this email is already registered.'}, max_length=255, unique=True)),
                ('custom_link', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('drive_folder_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_upload_id', models.CharField(editable=False, max_length=16, null=True)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='clients.client')),
            ],
        ),
    ]
