# Generated by Django 5.1.4 on 2024-12-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
