# Generated by Django 5.1.4 on 2024-12-18 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_custom_link_clientupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_email',
            field=models.EmailField(error_messages={'unique': 'Um cliente com este e-mail já está cadastrado.'}, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
