# Generated by Django 5.1.4 on 2024-12-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_client_client_email_alter_client_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='drive_folder_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
