# Generated by Django 5.1.4 on 2024-12-20 12:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_remove_client_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_email',
            field=models.EmailField(error_messages={'unique': 'A customer with this email is already registered.'}, max_length=255, unique=True),
        ),
    ]
